import type { Product } from "./types";

// Curated fallback catalogue — the demo must survive dead WiFi.
// `image: ""` renders the striped placeholder; swap in curated photo URLs later.
// Two halves: the desk/minimal set the demo starts on, and the camping set the
// voice shift pivots to, plus a few fits/home items so every chip has content.

const p = (
  id: string,
  title: string,
  price: number,
  merchant: string,
  link: string,
  tags: string[],
  description: string,
  salePct: number | null = null,
): Product => ({
  id,
  title,
  price,
  currency: "CAD",
  salePct,
  merchant,
  image: "",
  gallery: [],
  link,
  tags,
  description,
  galleryToken: null,
});

export const FALLBACK_FEED: Product[] = [
  // ── camping set (the vibe-shift destination) ──────────────────────────────
  p(
    "tent-sage",
    "2-person tent, sage",
    249,
    "MEC",
    "https://www.mec.ca/en/products/camping-and-hiking/tents",
    ["camping", "earth-tones", "waterproof"],
    "Freestanding, 3-season, 2.1 kg. Sets up in four minutes and shrugs off a Squamish downpour. Muted sage fly, zero neon.",
    15,
  ),
  p(
    "rain-jacket-olive",
    "Olive rain shell",
    179,
    "REI",
    "https://www.rei.com/c/rain-jackets",
    ["camping", "earth-tones", "waterproof", "fits"],
    "3-layer shell in deep olive. Pit zips, helmet-ready hood, packs into its own pocket.",
    10,
  ),
  p(
    "camp-mug",
    "Enamel camp mug",
    24,
    "MEC",
    "https://www.mec.ca/en/products/camping-and-hiking/camp-kitchen",
    ["camping", "earth-tones", "home"],
    "Speckled cream enamel over steel. Survives the fire ring, looks good on the shelf after.",
  ),
  p(
    "wool-blanket",
    "Wool camp blanket",
    139,
    "Pendleton",
    "https://www.pendleton-usa.com/blankets/",
    ["camping", "earth-tones", "home"],
    "Heavy virgin wool in muted stripe. Warm at 2 a.m., decor by daylight.",
  ),
  p(
    "sleeping-bag",
    "Down sleeping bag, −7°C",
    329,
    "MEC",
    "https://www.mec.ca/en/products/camping-and-hiking/sleeping-bags",
    ["camping", "waterproof", "earth-tones"],
    "650-fill down with a water-repellent shell. Rust-orange interior, moss exterior.",
  ),
  p(
    "camp-stove",
    "Two-burner camp stove",
    189,
    "MEC",
    "https://www.mec.ca/en/products/camping-and-hiking/camp-kitchen",
    ["camping"],
    "Push-start ignition, wind panels, simmers like a real range. Coffee before rain.",
  ),
  p(
    "headlamp",
    "Rechargeable headlamp",
    59,
    "REI",
    "https://www.rei.com/c/headlamps",
    ["camping", "minimal"],
    "400 lumens, warm-light mode, USB-C. Matte charcoal — not a single flashing RGB diode.",
  ),
  p(
    "rain-pants",
    "Packable rain pants",
    119,
    "Arc'teryx",
    "https://arcteryx.com/",
    ["camping", "waterproof", "fits"],
    "Full side zips over boots. Quiet fabric, quieter colour.",
    20,
  ),
  p(
    "trail-boots",
    "Leather trail boots",
    229,
    "Danner",
    "https://www.danner.com/",
    ["camping", "earth-tones", "vintage", "fits"],
    "Full-grain leather, resoleable, waterproof liner. The pair you keep for a decade.",
  ),
  p(
    "dry-bag",
    "Roll-top dry bag 20L",
    44,
    "MEC",
    "https://www.mec.ca/en/products/packs-and-bags",
    ["camping", "waterproof"],
    "Welded seams, ochre yellow. Everything inside stays bone dry.",
  ),
  p(
    "camp-chair",
    "Low camp chair, canvas",
    89,
    "Snow Peak",
    "https://snowpeak.com/",
    ["camping", "earth-tones", "home"],
    "Oiled bamboo arms, khaki canvas sling. Sits low by the fire.",
  ),
  p(
    "thermos",
    "1L insulated bottle",
    49,
    "Stanley",
    "https://www.stanley1913.com/",
    ["camping", "vintage"],
    "Hammertone green classic. Keeps coffee hot from trailhead to summit.",
  ),
  p(
    "tarp",
    "Ultralight tarp shelter",
    159,
    "MEC",
    "https://www.mec.ca/en/products/camping-and-hiking/tents",
    ["camping", "waterproof", "minimal"],
    "Sil-nylon in stone grey. 480 g of rain insurance for the cook area.",
  ),
  p(
    "merino-base",
    "Merino base layer",
    99,
    "Icebreaker",
    "https://www.icebreaker.com/",
    ["camping", "fits", "earth-tones"],
    "200-weight merino in heather bark. Warm when damp, no stink by day three.",
  ),
  p(
    "lantern",
    "Collapsible camp lantern",
    39,
    "MEC",
    "https://www.mec.ca/en/products/camping-and-hiking",
    ["camping", "minimal"],
    "Warm 300-lumen glow, packs flat to a puck. Card games after dark.",
  ),

  // ── desk / minimal set (where the demo starts) ────────────────────────────
  p(
    "walnut-shelf",
    "Walnut monitor shelf",
    129,
    "Grovemade",
    "https://grovemade.com/",
    ["desk", "minimal", "earth-tones", "home"],
    "Solid walnut riser with a steel base. Hides the cable mess underneath.",
  ),
  p(
    "keyboard-lowprofile",
    "Low-profile mechanical keyboard",
    159,
    "Keychron",
    "https://www.keychron.com/",
    ["desk", "minimal"],
    "Cream case, tactile switches, no backlight rave. Types like rain on a roof.",
    10,
  ),
  p(
    "desk-pad-linen",
    "Linen desk pad",
    45,
    "Grovemade",
    "https://grovemade.com/",
    ["desk", "minimal", "earth-tones"],
    "Natural flax linen over wool felt. Softens the whole desk, mutes the clacks.",
  ),
  p(
    "task-lamp-brass",
    "Brass task lamp",
    189,
    "Gantri",
    "https://www.gantri.com/",
    ["desk", "vintage", "home"],
    "Warm 2700K over aged brass. An anglepoise silhouette without the office energy.",
  ),
  p(
    "cable-kit",
    "Braided cable kit, sand",
    29,
    "Native Union",
    "https://www.nativeunion.com/",
    ["desk", "minimal"],
    "Cotton-braided USB-C set in sand and slate. The last visible cables you'll tolerate.",
  ),
  p(
    "notebook-a5",
    "A5 dot-grid notebook",
    24,
    "Baron Fig",
    "https://baronfig.com/",
    ["desk", "minimal", "vintage"],
    "Lay-flat binding, cream pages, linen cover. Analog buffer for digital work.",
  ),
  p(
    "chair-ergonomic",
    "Ergonomic task chair, oat",
    549,
    "Branch",
    "https://www.branchfurniture.com/",
    ["desk", "home", "minimal"],
    "Full adjustability in an oat wool weave. Your back files no complaints.",
    15,
  ),
  p(
    "monitor-light",
    "Monitor light bar",
    79,
    "BenQ",
    "https://www.benq.com/",
    ["desk", "minimal"],
    "Asymmetric warm light on the desk, none on the screen. Auto-dims at dusk.",
  ),
  p(
    "rgb-light-bar",
    "RGB ambient light bar",
    69,
    "Govee",
    "https://www.govee.com/",
    ["desk", "rgb", "neon"],
    "16 million colours synced to your screen. Maximum glow, maximum vibe — if that's your vibe.",
  ),
  p(
    "gaming-mouse",
    "Wireless gaming mouse, neon",
    99,
    "Razer",
    "https://www.razer.com/",
    ["desk", "rgb", "neon"],
    "26K DPI, chroma lighting, 90-hour battery. Glows like a small city.",
  ),

  // ── fits / home extras ────────────────────────────────────────────────────
  p(
    "chore-coat",
    "Waxed chore coat",
    198,
    "Taylor Stitch",
    "https://www.taylorstitch.com/",
    ["fits", "vintage", "earth-tones", "waterproof"],
    "Waxed canvas in field tan. Sheds drizzle, gains character with every scuff.",
  ),
  p(
    "selvedge-denim",
    "Selvedge denim, indigo",
    168,
    "Naked & Famous",
    "https://www.nakedandfamousdenim.com/",
    ["fits", "vintage", "streetwear"],
    "13.75 oz Japanese selvedge. Stiff for a month, perfect for a decade.",
  ),
  p(
    "canvas-sneaker",
    "Canvas court sneaker, ecru",
    95,
    "Vans",
    "https://www.vans.com/",
    ["fits", "streetwear", "minimal"],
    "Off-white canvas, gum sole. Goes with literally everything above.",
  ),
  p(
    "ceramic-pourover",
    "Ceramic pour-over set",
    68,
    "Fellow",
    "https://fellowproducts.com/",
    ["home", "minimal", "earth-tones"],
    "Matte clay dripper and double-wall carafe. Slow coffee for fast mornings.",
  ),
  p(
    "linen-throw",
    "Stonewashed linen throw",
    120,
    "Parachute",
    "https://www.parachutehome.com/",
    ["home", "earth-tones", "minimal"],
    "Heavy flax linen in terracotta. The couch upgrade guests always ask about.",
    10,
  ),
];
